export const GET_STANDINGS = 'GET_STANDINGS';
export const LOG_GET_STANDINGS = 'LOG_GET_STANDINGS';

export const GET_TEAMS = 'GET_TEAMS';
export const LOG_GET_TEAMS = 'LOG_GET_TEAMS';

export const GET_DIVISION = 'GET_DIVISION';
export const LOG_GET_DIVISION = 'LOG_GET_DIVISION';
export const GET_DIVISIONS = 'GET_DIVISIONS';
export const LOG_GET_DIVISIONS = 'LOG_GET_DIVISIONS';

export const GET_CONFERENCE = 'GET_CONFERENCE';
export const LOG_GET_CONFERENCE = 'LOG_GET_CONFERENCE';
export const GET_CONFERENCES = 'GET_CONFERENCES';
export const LOG_GET_CONFERENCES = 'LOG_GET_CONFERENCES';

export const GET_SCHEDULE = 'GET_SCHEDULE';
export const LOG_GET_SCHEDULE = 'LOG_GET_SCHEDULE';
